[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.105.0"

[[headers]]
  for = "/.well-known/nostr.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
